services:
  - type: web
    name: vinyls-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: vinyls-backend
          property: port
    plan: free
    
databases:
  - name: vinyls-db
    plan: free
    databaseName: vinyls
    user: vinyls_user

